supportedExtensions:
  ".java": "JAVA"
  ".jsp": "JSP"
  ".jspf": "JSP"
  ".tag": "JSP"
  ".tagx": "JSP"
  ".tld": "TLD"
  ".jspx": "JSPX"
  ".xhtml": "JSPX"
  ".faces": "JSPX"
  ".jsff": "JSPX"
  ".scala": "SCALA"
  ".js": "TYPESCRIPT"
  ".mjs": "TYPESCRIPT"
  ".cjs": "TYPESCRIPT"
  ".jsx": "TYPESCRIPT"
  ".ts": "TYPESCRIPT"
  ".mts": "TYPESCRIPT"
  ".cts": "TYPESCRIPT"
  ".tsx": "TYPESCRIPT"
  ".vue": "VUE"
  ".php": "PHP"
  ".phtml": "PHP"
  ".ctp": "PHP"
  ".py": "PYTHON"
  ".htm": "HTML"
  ".html": "HTML"
  ".sql": "SQL"
  ".pls": "PLSQL"
  ".pks": "PLSQL"
  ".pkh": "PLSQL"
  ".pkb": "PLSQL"
  ".xml": "XML"
  ".xsd": "XML"
  ".xmi": "XML"
  ".wsdd": "XML"
  ".config": "XML"
  ".Config": "XML"
  ".settings": "XML"
  ".cpx": "XML"
  ".xcfg": "XML"
  ".cscfg": "XML"
  ".csdef": "XML"
  ".wadcfg": "XML"
  ".wadcfgx": "XML"
  ".appxmanifest": "XML"
  ".wsdl": "XML"
  ".plist": "XML"
  ".json": "JSON"
  ".conf": "HOCON"
  ".yaml": "YAML"
  ".yml": "YAML"
  ".hcl": "FLIGHT"
  ".tf": "FLIGHT"
  ".properties": "JAVA_PROPERTIES"
  ".ini": "JAVA_PROPERTIES"
  ".cfm": "CFML"
  ".cfml": "CFML"
  ".cfc": "CFML"
  ".exe": "MSIL"
  ".dll": "MSIL"
  ".winmd": "MSIL"
  ".mod": "MSIL"
  ".mdl": "MSIL"
  ".baml": "MSIL"
  ".cbl": "COBOL"
  ".cob": "COBOL"
  ".cs": "CSHARP"
  ".vb": "VB"
  ".aspx": "ASPNET"
  ".ascx": "ASPNET"
  ".asax": "ASPNET"
  ".ashx": "ASPNET"
  ".asmx": "ASPNET"
  ".master": "ASPNET"
  ".Master": "ASPNET"
  ".xaml": "ASPNET"
  ".cshtml": "ASPNET"
  ".vbhtml": "ASPNET"
  ".axml": "ASPNET"
  ".razor": "ASPNET"
  ".asp": "ASP"
  ".vbscript": "VBSCRIPT"
  ".vbs": "VBSCRIPT"
  ".bas": "VB6"
  ".frm": "VB6"
  ".ctl": "VB6"
  ".cls": "APEX"
  ".object": "APEX_OBJECT"
  ".trigger": "APEX_TRIGGER"
  ".abap": "ABAP"
  ".ABAP": "ABAP"
  ".bsp": "ABAP"
  ".BSP": "ABAP"
  ".as": "ACTIONSCRIPT"
  ".mxml": "MXML"
  ".rb": "RUBY"
  ".erb": "RUBY_ERB"
  ".swift": "SWIFT"
  ".page": "VISUAL_FORCE"
  ".component": "VISUAL_FORCE"
  ".go": "GO"
  ".kt": "KOTLIN"
  ".kts": "KOTLIN"
  ".dart": "DART"
  ".Dockerfile": "DOCKERFILE"
  ".dockerfile": "DOCKERFILE"
  ".sol": "SOLANA"
  ".bicep": "BICEP"
  ".template": "ARM"
  ".SqlLanguage": "TSQL"
